Repository UBBGenzie/cv-builder, pull requests merged in 2025-05, with the labels that each got.

#11 feat: all CV sections implemented (frontend only)
  package-lock.json
  package.json
  src/app/globals.css
  src/app/layout.js
  src/app/page.js
  src/components/CertificationForm.jsx
  src/components/EducationForm.jsx
  src/components/ExperienceForm.jsx
  src/components/PersonalDataForm.jsx
  src/components/ProfileForm.jsx
  src/components/ProjectsForm.jsx
  src/components/SkillsForm.jsx
  src/store/cvStore.js
Labels: Frontend/UI

#12 Feature/summary page
  .eslintrc.json
  .gitignore
  .prettierrc
  README.md
  eslint.config.mjs
  jsconfig.json
  next.config.mjs
  package-lock.json
  package.json
  postcss.config.mjs
  src/app/globals.css
  src/app/layout.js
  src/app/page.js
  src/app/summary/page.jsx
  src/components/CVPreview.jsx
  src/components/CertificationForm.jsx
  src/components/EducationForm.jsx
  src/components/ExperienceForm.jsx
  src/components/PersonalDataForm.jsx
  src/components/ProfileForm.jsx
  src/components/ProjectsForm.jsx
  src/components/SkillsForm.jsx
  src/store/cvStore.js
Labels: programmer task

#15 feat: export CV as PDF using html2pdf.js
  package-lock.json
  package.json
  src/app/page.js
  src/components/CVPreview.jsx
  src/components/PdfDownloadButton.jsx
  src/components/PersonalDataForm.jsx
Labels: programmer task

#16 feat: add localStorage persist with reset button
  src/app/page.js
  src/components/PersonalDataForm.jsx
  src/components/ResetCVButton.jsx
  src/store/cvStore.js
Labels: programmer task

#18 Develop
  package-lock.json
  package.json
  src/app/globals.css
  src/app/layout.js
  src/app/page.js
  src/app/summary/page.jsx
  src/components/CVPreview.jsx
  src/components/CertificationForm.jsx
  src/components/CertificationPopup.jsx
  src/components/CertificationsList.jsx
  src/components/EducationForm.jsx
  src/components/EducationList.jsx
  src/components/EducationPopup.jsx
  src/components/ExperienceForm.jsx
  src/components/ExperienceList.jsx
  src/components/ExperiencePopup.jsx
  src/components/ItemList.jsx
  src/components/ItemPopup.jsx
  src/components/LanguagesList.jsx
  src/components/LanguagesPopup.jsx
  src/components/PdfDownloadButton.jsx
  src/components/PersonalDataForm.jsx
  src/components/Popup.jsx
  src/components/ProfileForm.jsx
  src/components/ProfilePopup.jsx
  src/components/ProfilesList.jsx
  src/components/ProjectsForm.jsx
  src/components/ProjectsList.jsx
  src/components/ProjectsPopup.jsx
  src/components/ResetCVButton.jsx
  src/components/Section.jsx
  src/components/SkillsForm.jsx
  src/components/SkillsList.jsx
  src/components/SkillsPopup.jsx
  src/store/cvStore.js
  src/styles/formStyles.js
Labels: Github
